create extension if not exists citext with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated, service_role;

create table public.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  status text not null default 'active' check (status in ('active', 'suspended', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tenant_members (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'sales' check (role in ('owner', 'admin', 'manager', 'sales', 'viewer')),
  created_at timestamptz not null default now(),
  unique (tenant_id, user_id)
);

create table public.sites (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  public_id uuid not null default gen_random_uuid() unique,
  name text not null check (char_length(name) between 2 and 120),
  base_url text not null,
  allowed_origins text[] not null default '{}',
  status text not null default 'active' check (status in ('active', 'paused', 'revoked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, base_url)
);

create table private.site_credentials (
  site_id uuid primary key references public.sites(id) on delete cascade,
  write_token_hash text not null,
  rotated_at timestamptz not null default now()
);

create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  site_id uuid references public.sites(id) on delete set null,
  email extensions.citext not null,
  first_name text not null default '',
  last_name text not null default '',
  phone text not null default '',
  company text not null default '',
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'customer', 'lost')),
  source text not null default 'website',
  owner_user_id uuid references auth.users(id) on delete set null,
  marketing_consent boolean not null default false,
  consent_recorded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, email)
);

create table public.visitors (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  site_id uuid not null references public.sites(id) on delete cascade,
  visitor_uuid uuid not null,
  contact_id uuid references public.contacts(id) on delete set null,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  first_landing_url text,
  first_referrer text,
  locale text not null default '',
  device_type text not null default '',
  sessions_count integer not null default 0 check (sessions_count >= 0),
  pageviews_count integer not null default 0 check (pageviews_count >= 0),
  engagement_score integer not null default 0 check (engagement_score between 0 and 100),
  unique (site_id, visitor_uuid)
);

create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  site_id uuid not null references public.sites(id) on delete cascade,
  visitor_id uuid not null references public.visitors(id) on delete cascade,
  session_uuid uuid not null,
  started_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  landing_url text,
  referrer text,
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  unique (site_id, session_uuid)
);

create table public.events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  site_id uuid not null references public.sites(id) on delete cascade,
  visitor_id uuid not null references public.visitors(id) on delete cascade,
  session_id uuid not null references public.sessions(id) on delete cascade,
  request_id uuid not null,
  event_type text not null check (event_type in ('page_view', 'click', 'scroll', 'heartbeat', 'form_started', 'form_submitted', 'download', 'voice_intent')),
  page_url text,
  page_title text not null default '',
  element_name text not null default '',
  event_data jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  unique (site_id, request_id)
);

create table public.activities (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  site_id uuid references public.sites(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete cascade,
  visitor_id uuid references public.visitors(id) on delete set null,
  activity_type text not null,
  subject text not null default '',
  body text,
  metadata jsonb not null default '{}'::jsonb,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table private.ingest_requests (
  id bigint generated by default as identity primary key,
  site_id uuid not null references public.sites(id) on delete cascade,
  request_id uuid not null,
  received_at timestamptz not null default now(),
  unique (site_id, request_id)
);

create index visitors_tenant_last_seen_idx on public.visitors (tenant_id, last_seen desc);
create index visitors_site_score_idx on public.visitors (site_id, engagement_score desc);
create index sessions_visitor_activity_idx on public.sessions (visitor_id, last_activity_at desc);
create index events_tenant_occurred_idx on public.events (tenant_id, occurred_at desc);
create index events_visitor_occurred_idx on public.events (visitor_id, occurred_at desc);
create index contacts_tenant_status_idx on public.contacts (tenant_id, status, updated_at desc);
create index activities_contact_created_idx on public.activities (contact_id, created_at desc);
create index ingest_requests_site_received_idx on private.ingest_requests (site_id, received_at desc);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger tenants_set_updated_at before update on public.tenants
for each row execute function private.set_updated_at();
create trigger sites_set_updated_at before update on public.sites
for each row execute function private.set_updated_at();
create trigger contacts_set_updated_at before update on public.contacts
for each row execute function private.set_updated_at();

create or replace function private.is_tenant_member(p_tenant_id uuid)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.tenant_members tm
    where tm.tenant_id = p_tenant_id
      and tm.user_id = (select auth.uid())
  );
$$;

create or replace function private.has_tenant_role(p_tenant_id uuid, p_roles text[])
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.tenant_members tm
    where tm.tenant_id = p_tenant_id
      and tm.user_id = (select auth.uid())
      and tm.role = any (p_roles)
  );
$$;

revoke all on function private.is_tenant_member(uuid) from public, anon;
revoke all on function private.has_tenant_role(uuid, text[]) from public, anon;
grant execute on function private.is_tenant_member(uuid) to authenticated;
grant execute on function private.has_tenant_role(uuid, text[]) to authenticated;

create or replace function public.verify_site_token(p_site_public_id uuid, p_token_hash text)
returns table (
  site_id uuid,
  tenant_id uuid,
  base_url text,
  allowed_origins text[]
)
language sql
security definer
stable
set search_path = ''
as $$
  select s.id, s.tenant_id, s.base_url, s.allowed_origins
  from public.sites s
  join private.site_credentials sc on sc.site_id = s.id
  join public.tenants t on t.id = s.tenant_id
  where s.public_id = p_site_public_id
    and sc.write_token_hash = p_token_hash
    and s.status = 'active'
    and t.status = 'active'
  limit 1;
$$;

revoke all on function public.verify_site_token(uuid, text) from public, anon, authenticated;
grant execute on function public.verify_site_token(uuid, text) to service_role;

alter table public.tenants enable row level security;
alter table public.tenant_members enable row level security;
alter table public.sites enable row level security;
alter table public.contacts enable row level security;
alter table public.visitors enable row level security;
alter table public.sessions enable row level security;
alter table public.events enable row level security;
alter table public.activities enable row level security;

create policy tenants_select_member on public.tenants
for select to authenticated
using (private.is_tenant_member(id));

create policy tenant_members_select_member on public.tenant_members
for select to authenticated
using (private.is_tenant_member(tenant_id));

create policy sites_select_member on public.sites
for select to authenticated
using (private.is_tenant_member(tenant_id));

create policy sites_manage_admin on public.sites
for all to authenticated
using (private.has_tenant_role(tenant_id, array['owner', 'admin']))
with check (private.has_tenant_role(tenant_id, array['owner', 'admin']));

create policy contacts_select_member on public.contacts
for select to authenticated
using (private.is_tenant_member(tenant_id));

create policy contacts_manage_sales on public.contacts
for all to authenticated
using (private.has_tenant_role(tenant_id, array['owner', 'admin', 'manager', 'sales']))
with check (private.has_tenant_role(tenant_id, array['owner', 'admin', 'manager', 'sales']));

create policy visitors_select_member on public.visitors
for select to authenticated
using (private.is_tenant_member(tenant_id));

create policy sessions_select_member on public.sessions
for select to authenticated
using (private.is_tenant_member(tenant_id));

create policy events_select_member on public.events
for select to authenticated
using (private.is_tenant_member(tenant_id));

create policy activities_select_member on public.activities
for select to authenticated
using (private.is_tenant_member(tenant_id));

create policy activities_manage_sales on public.activities
for all to authenticated
using (private.has_tenant_role(tenant_id, array['owner', 'admin', 'manager', 'sales']))
with check (private.has_tenant_role(tenant_id, array['owner', 'admin', 'manager', 'sales']));

grant select on public.tenants, public.tenant_members, public.sites, public.contacts,
  public.visitors, public.sessions, public.events, public.activities to authenticated;
grant insert, update, delete on public.contacts, public.activities to authenticated;
grant insert, update, delete on public.sites to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on private.site_credentials, private.ingest_requests from public, anon, authenticated;

